---
abstract: 'JSON session backend for Dancer'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  Dancer: 0
  English: 0
  File::Find: 0
  File::Path: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Session-JSON
requires:
  Carp: 0
  Dancer: 1.3012
  Dancer::Config: 0
  Dancer::FileUtils: 0
  Dancer::Logger: 0
  Dancer::ModuleLoader: 0
  Dancer::Session::Abstract: 0
  Fcntl: 0
  JSON: 0
resources:
  repository: http://github.com/xsawyerx/dancer-session-json
version: 0.001
